Python 3.0+ support and delete confirmation warning added
source-aasf/AutoDel pull request #1
Opened 2018-09-16 17:24 UTC by aquatiko

2018-09-16 18:21 UTC, ab-anand requested changes
Thanks for the PR @aquatiko 
But it won't work in Python2 with this import(plz correct me if I'm wrong).
Though nothing to worry, this is the change you might need to do https://stackoverflow.com/a/17843652/7276784
and also include that `messageBox` import in try/except block as explained in that answer. N make sure it works with both the versions. N try sticking to the PEP-8 or just use the Python-beautifier XD

Bdw the messageBox work is nice :)

2018-09-17 10:26 UTC, aquatiko commented
Added python2 support and removed "all_files" variable as there is only a need for iteration and storing, retrieving and passing would increase execution time. Still having doubts, as how to use generators here??

2018-09-17 13:02 UTC, ab-anand commented
@aquatiko It looks good, it surely is memory efficient but I'm not sure whether it wld speed up the process or not.
A small task for u if u choose to accept.

check this: https://stackoverflow.com/a/6791946/7276784
We can check out the time taken through this method(though there are many other ways). 

In the code put the `start timer` during the start of `delete` function and `end_timer` at the end. In the final notification return the time difference e.g. `232 files deleted in 1.0232 seconds` and compare urs with mine. Try deleting files from a test folder with 5-6 GB of files of any kind.

Anyways even at this point, the PR wld surely work fine. So, I'm merging it :)
But u can give another PR when u r done with that task. Also, that generator thing was just an example to speed up stuff, it might not be applicable here.

2018-09-17 13:02 UTC, ab-anand approved these changes

2018-09-17 13:03 UTC, ab-anand approved these changes

2018-09-17 13:18 UTC, merged